version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: core-master
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "pk2258"]
    networks:
      - redis-net

#  redis-slave-1:
#    image: redis:latest
#    container_name: redis-slave-1
#    ports:
#      - "6380:6379"
#    command: ["redis-server", "--slaveof", "redis-master", "6379", "--requirepass", "pk2258", "--masterauth", "pk2258", "--repl-ping-replica-period", "10", "--repl-timeout", "60"]
#    networks:
#      - redis-net

#  redis-slave-2:
#    image: redis:latest
#    container_name: redis-slave-2
#    ports:
#      - "6381:6379"
#    command: ["redis-server", "--slaveof", "redis-master", "6379", "--requirepass", "pk2258", "--masterauth", "pk2258", "--repl-ping-replica-period", "10", "--repl-timeout", "60"]
#    networks:
#      - redis-net

networks:
  redis-net:
    driver: bridge
